DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS joke;

DROP TABLE IF EXISTS review;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  nickname TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  balance INTEGER,
  role TEXT NOT NULL
);

CREATE TABLE joke (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  UNIQUE (title, author_id),
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE review (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  joke_id INTEGER NOT NULL,
  rating INTEGER NOT NULL,
  rated_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, joke_id),
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (joke_id) REFERENCES joke (attribute)
);
